version: '3.9'
services:
  backend:
    platform: linux/amd64
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: backend
    env_file:
      - backend/.env
    environment:
      TZ: Asia/Seoul
    ports:
      - '4000:4000'
    extra_hosts:
      - 'host.docker.internal:host-gateway'
