name: Build and Push Docker Image to ECR

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: false
        default: 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CICD_ROLE_ARN }}
          role-sesion-name: GitHubActions
          aws-region: ap-northeast-2

      # - name: Assume AWS Role
      #   run: aws sts assume-role --role-arn arn:aws:iam::<your-account-id>:role/<your-role-name> --role-session-name GitHubActions --output json > assumed-credentials.json

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v1

      # - name: Build Docker image
      #   run: |
      #     docker buildx create --use
      #     docker buildx build --platform linux/amd64,linux/arm64 -t <your-image-name> .

      # - name: Authenticate ECR
      #   id: ecr
      #   run: |
      #     aws ecr get-login-password --region <your-region> | docker login --username AWS --password-stdin <your-account-id>.dkr.ecr.<your-region>.amazonaws.com

      # - name: Tag and Push Docker image to ECR
      #   run: |
      #     docker tag <your-image-name>:latest <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/<your-repository-name>:latest
      #     docker push <your-account-id>.dkr.ecr.<your-region>.amazonaws.com/<your-repository-name>:latest
