name: Build and Push Docker Image to ECR

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch name'
        required: false
        default: 'main'
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_CICD_ROLE_ARN }}
          role-session-name: GitHubActions
          aws-region: ap-northeast-2
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
      # - name: Set Datetime
      #   id: datetime
      #   run: echo "DATETIME=$(date + '%Y-%s-%dT%H:%M:%S')" >> %GITHUB_ENV
      - name: echo refs/tag
        run: echo ${{ github.ref }}
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ secrets.AWS_ECR_REPOSITORY }}
          IMAGE_TAG: ${{ github.sha }}
          DATETIME: $(date + '%Y-%s-%dT%H:%M:%S')
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$DATETIME .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$DATETIME
