name: Build and Push Docker Image to ECR

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: false
        default: "main"
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set Datetime
        id: datetime
        run: echo "DATETIME=$(date + '%Y-%s-%dT%H:%M:%S')" >> %GITHUB_ENV
      - name: echo date
        run: echo $DATETIME
