name: date-test

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch name"
        required: false
        default: "main"
permissions:
  id-token: write
  contents: read
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set test env
        id: test-env
        run: echo "NAME=john" >> "$GITHUB_ENV"
      - name: echo name
        run: echo "$NAME"
      - name: Set Datetime
        id: datetime
        run: echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV
      - name: echo date
        run: echo "$DATE"
